package bookstore.database;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Bookinfo generated by MyEclipse - Hibernate Tools
 */

public class Bookinfo  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String bookName;
     private String isbn;
     private String writer;
     private String publisher;
     private String intro;
     private double price;
     private short remaining;
     private String picture;
     private Date date;
     private Set orders = new HashSet(0);
     private Set remarks = new HashSet(0);


    // Constructors

    /** default constructor */
    public Bookinfo() {
    }

	/** minimal constructor */
    public Bookinfo(String bookName, String isbn, String writer, String publisher, double price, short remaining, Date date) {
        this.bookName = bookName;
        this.isbn = isbn;
        this.writer = writer;
        this.publisher = publisher;
        this.price = price;
        this.remaining = remaining;
        this.date = date;
    }
    
    /** full constructor */
    public Bookinfo(String bookName, String isbn, String writer, String publisher, String intro, double price, short remaining, String picture, Date date, Set orders, Set remarks) {
        this.bookName = bookName;
        this.isbn = isbn;
        this.writer = writer;
        this.publisher = publisher;
        this.intro = intro;
        this.price = price;
        this.remaining = remaining;
        this.picture = picture;
        this.date = date;
        this.orders = orders;
        this.remarks = remarks;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getWriter() {
        return this.writer;
    }
    
    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getIntro() {
        return this.intro;
    }
    
    public void setIntro(String intro) {
        this.intro = intro;
    }

    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    public short getRemaining() {
        return this.remaining;
    }
    
    public void setRemaining(short remaining) {
        this.remaining = remaining;
    }

    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }

    public Set getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Set remarks) {
        this.remarks = remarks;
    }
   








}