package bookstore.database;



/**
 * Rebate generated by MyEclipse - Hibernate Tools
 */

public class Rebate  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private double level;
     private double rebateRate;


    // Constructors

    /** default constructor */
    public Rebate() {
    }

    
    /** full constructor */
    public Rebate(double level, double rebateRate) {
        this.level = level;
        this.rebateRate = rebateRate;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public double getLevel() {
        return this.level;
    }
    
    public void setLevel(double level) {
        this.level = level;
    }

    public double getRebateRate() {
        return this.rebateRate;
    }
    
    public void setRebateRate(double rebateRate) {
        this.rebateRate = rebateRate;
    }
   








}