package bookstore.database;

import java.util.HashSet;
import java.util.Set;


/**
 * Userinfo generated by MyEclipse - Hibernate Tools
 */

public class Userinfo  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
     private String username;
     private String pwd;
     private String email;
     private String address;
     private String postcode;
     private double level;
     private Set remarks = new HashSet(0);
     private Set orders = new HashSet(0);
     private short power;


    // Constructors

    /** default constructor */
    public Userinfo() {
    }

	/** minimal constructor */
    public Userinfo(String username, String pwd, String email) {
        this.username = username;
        this.pwd = pwd;
        this.email = email;
    }
    
    /** full constructor */
    public Userinfo(String username, String pwd, String email, String address, String postcode, double level, Set remarks, Set orders) {
        this.username = username;
        this.pwd = pwd;
        this.email = email;
        this.address = address;
        this.postcode = postcode;
        this.level = level;
        this.remarks = remarks;
        this.orders = orders;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public double getLevel() {
        return this.level;
    }
    
    public void setLevel(double level) {
        this.level = level;
    }

    public Set getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Set remarks) {
        this.remarks = remarks;
    }

    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }

    public short getPower() {
        return power;
    }

    public void setPower(short power) {
        this.power = power;
    }
    
}